FROM python:3.12-slim

ENV APP_HOME='/code'
WORKDIR $APP_HOME

ENV UV_SYSTEM_PYTHON=1
ENV UV_LINK_MODE=copy

RUN pip install --no-cache-dir --upgrade pip uv

COPY . .

RUN uv sync --no-dev

EXPOSE 8000

CMD ["uv", "run", "fastapi", "run", "--proxy-headers", "--port", "8000"]
